eureka:
  instance:
    prefer-ip-address: false
    hostname: fsstorage
  client:
    service-url:
      defaultZone: http://fseurekaserver:8761/eureka/,http://fseurekaserver2:8762/eureka/
spring:
  zipkin:
    base-url: http://zipkinserver:9411
logging:
  config: http://fsconfigserver:8888/fs-logback/default/master/logback-spring.xml
logstash:
  destination: 172.16.2.5:4567
uca:
  storage:
    path: /opt/uca/file/media/econtract