eureka:
  instance:
    ip-address: 192.168.100.212
  client:
    service-url:
      defaultZone: http://192.168.63.195:9761/eureka/
spring:
  datasource:
    url: jdbc:mysql://192.168.63.195:3306/plat_content
    username: uca
    password: "{cipher}9ec866e852875a2cafebae6fa27f35afdaad1afd8ad0eae53c3fb007932e3146"
  zipkin:
    base-url: http://192.168.63.195:9411
logging:
  config: http://192.168.63.195:9888/bs-logback/default/master/logback-spring.xml
logstash:
  destination: 192.168.63.195:4567