eureka:
  instance:
    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://127.0.0.1:9761/eureka/
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/plat_corporate?allowMultiQueries=true
    username: andy
    password: "{cipher}80c7ea7a7da7410a66acdfe199ec28efa8c31616466f5963d9a364ba81d425c5"
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: "{cipher}2df160dcfd591bcc30397e5884b385ce2da74e1247299bc69e99468d92b3eb23"
logging:
  config: http://127.0.0.1:9888/bs-logback/default/master/logback-spring.xml
logstash:
  destination: 127.0.0.1:4567