eureka:
  instance:
    prefer-ip-address: false
    hostname: bsopsmsgpush
  client:
    service-url:
      defaultZone: http://bseurekaserver:9761/eureka/,http://bseurekaserver2:9762/eureka/
spring:
  datasource:
    url: jdbc:mysql://120.77.46.84:3306/finance_ops_sys
    username: uca
    password: "{cipher}698554aab5fb42360efdd645be1dcfc47d2200496fd6a9329898dcf7fbaa7748"
  zipkin:
    base-url: http://bszipkinserver:9411
  rabbitmq:
    host: 172.16.2.6
    port: 5672
    username: guest
    password: "{cipher}2df160dcfd591bcc30397e5884b385ce2da74e1247299bc69e99468d92b3eb23"
logging:
  config: http://bsconfigserver:9888/bs-logback/default/master/logback-spring.xml
logstash:
  destination: 172.16.2.5:4567