eureka:
  instance:
    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/plat_msgpush
    username: andy
    password: "{cipher}ba650aff4c287756d58513e7ad127edfc125d6307ce0c1757120f85eadb165ea"
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: "{cipher}257b9b2287a88191dd6e43979c7ef67d87c82b15d60da332c8ca4b22285fc03e"
logging:
  config: http://127.0.0.1:8888/fs-logback/default/master/logback-spring.xml
logstash:
  destination: 127.0.0.1:4567
uca:
  plat:
    msg-push:
      fs:
        sms-msg-push:
          password: "{cipher}d83c03af3c18c1eaa93591065a5977b72dbc68b24c5ee8aa1e0298ab3786015d"