eureka:
  instance:
    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://127.0.0.1:9761/eureka/
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/plat_sys
    username: andy
    password: "{cipher}5e333696e1b8ec895675c93c4ec6116a2b26c4997d4fe8578a2f8491896243b8"
logging:
  config: http://127.0.0.1:9888/bs-logback/default/master/logback-spring.xml
logstash:
  destination: 127.0.0.1:4567