eureka:
  instance:
    prefer-ip-address: false
    hostname: bspinganpay
  client:
    service-url:
      defaultZone: http://bseurekaserver:9761/eureka/,http://bseurekaserver2:9762/eureka/
spring:
  datasource:
    url: jdbc:mysql://rm-wz9y4h9rwvs17i4cv.mysql.rds.aliyuncs.com:3306/ping_an_pay
    username: ucacc1018
    password: "{cipher}d3e57249863c5a031cb73e111c6eb5985d1ce868c799887bb86912ff1c16b584"
  rabbitmq:
    host: 172.16.2.6
    port: 5672
    username: guest
    password: "{cipher}eb95f8788faf8ede3c482a026f6f70b5d87c16a77665e8af0ba493e6cc19aed6"
  zipkin:
    base-url: http://bszipkinserver:9411
  redis:
    host: 172.16.2.6
    port: 6379
logging:
  config: http://bsconfigserver:9888/bs-logback/default/master/logback-spring.xml
logstash:
  destination: 172.16.2.5:4567
ucacc:
  pingan:
    pay:
      security:
        password: "{cipher}c604169196314eb39c34fea9d96f27a8f33aff1fe5f6b8b96a4d2dffa6920128"
      b2biclient:
        url: http://172.16.2.6:7072
      bank:
        open-account-url: https://my-st1.orangebank.com.cn/corporbank/perRegedit_jsyb.do
        main-acct-id: 15000124617572
        platform-code: 9254
        platform-name: 众陶联