eureka:
  instance:
    ip-address: 192.168.100.207
  client:
    service-url:
      defaultZone: http://192.168.63.195:9761/eureka/
spring:
  datasource:
    url: jdbc:mysql://192.168.63.195:3306/ping_an_pay
    username: uca
    password: "{cipher}c604169196314eb39c34fea9d96f27a8f33aff1fe5f6b8b96a4d2dffa6920128"
  rabbitmq:
    host: 192.168.63.195
    port: 5672
    username: guest
    password: "{cipher}257b9b2287a88191dd6e43979c7ef67d87c82b15d60da332c8ca4b22285fc03e"
  zipkin:
    base-url: http://192.168.63.195:9411
  redis:
    host: 192.168.63.195
    port: 6379
logging:
  config: http://192.168.63.195:9888/bs-logback/default/master/logback-spring.xml
logstash:
  destination: 192.168.63.195:4567
ucacc:
  pingan:
    pay:
      security:
        password: "{cipher}c604169196314eb39c34fea9d96f27a8f33aff1fe5f6b8b96a4d2dffa6920128"
      b2biclient:
        url: http://192.168.63.195:7072
      bank:
        open-account-url: https://my-st1.orangebank.com.cn/corporbank/perRegedit_jsyb.do
        main-acct-id: 15000129814944
        platform-code: 1015
        platform-name: 众陶联开发环境