eureka:
  instance:
    prefer-ip-address: false
    hostname: bsplatfile
  client:
    serviceUrl:
      defaultZone: http://bseurekaserver:9761/eureka/,http://bseurekaserver2:9762/eureka/
spring:
  datasource:
    url: jdbc:mysql://rm-wz9y4h9rwvs17i4cv.mysql.rds.aliyuncs.com:3306/plat_file?allowMultiQueries=true
    username: ucacc1018
    password: "{cipher}bce2707ccb18fd06160cb677511d9c4164c20c069a39bf1e6706a7c663b2c519"
  redis:
    host: 172.16.2.6
    port: 6379
  zipkin:
    base-url: http://bszipkinserver:9411
logging:
  config: http://bsconfigserver:9888/bs-logback/default/master/logback-spring.xml
logstash:
  destination: 172.16.2.5:4567
uca:
  plat:
    file:
      # 统一以前台的入口来对附件进行下载
      url: https://testfile.ucacc.com/fs-plat-file
      exposed-location: /opt/uca/file
seata:
  service:
    grouplist:
      bs_seata: bsseataserver:9091