eureka:
  instance:
    ip-address: 192.168.100.212
  client:
    service-url:
      defaultZone: http://192.168.63.195:8761/eureka/
spring:
  datasource:
    url: jdbc:mysql://192.168.63.195:3306/plat_file?allowMultiQueries=true
    username: uca
    password: "{cipher}10c47294de6a815eb1f74edbc81687e75fd65bea4806066135b1624de25637f7"
  redis:
    host: 192.168.63.195
    port: 6379
  zipkin:
    base-url: http://192.168.63.195:8411
logging:
  config: http://192.168.63.195:8888/fs-logback/default/master/logback-spring.xml
logstash:
  destination: 192.168.63.195:4567
uca:
  plat:
    file:
      url: http://192.168.63.195:8555/fs-plat-file
      exposed-location: /opt/uca/file
