eureka:
  instance:
    prefer-ip-address: false
    hostname: fsplatfile
  client:
    serviceUrl:
      defaultZone: http://fseurekaserver:8761/eureka/
spring:
  datasource:
    url: jdbc:mysql://172.16.2.3:3306/plat_file?allowMultiQueries=true
    username: developer
    password: "{cipher}1ce9b466bb25531a0d4ed5cf5749d37428b854cadac09ec43d9499aa32dd5d09"
  redis:
    host: 172.16.2.6
    port: 6379
  zipkin:
    base-url: http://fszipkinserver:8411
logging:
  config: http://fsconfigserver:8888/fs-logback/default/master/logback-spring.xml
logstash:
  destination: 172.16.2.5:4567
uca:
  plat:
    file:
      url: http://testapi.ucacc.com/fs-plat-file
      exposed-location: /opt/uca/file