eureka:
  instance:
    prefer-ip-address: false
    hostname: fsrawmaterial
  client:
    service-url:
      defaultZone: http://fseurekaserver:8761/eureka/
spring:
  zipkin:
    base-url: http://fszipkinserver:8411
  rabbitmq:
    host: 172.16.2.6
    port: 5672
    username: guest
    password: "{cipher}eb95f8788faf8ede3c482a026f6f70b5d87c16a77665e8af0ba493e6cc19aed6"
uca:
  front-staging-url: https://master.ucacc.com
  global:
    mq:
      enable: true
  jdbc:
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 10
    maxIdle: 15
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    maxOpenPreparedStatements: 20
    removeAbandonedTimeout: 1800
 # 测试环境
    url: jdbc:mysql://172.16.2.3:3306/masterdb3?zeroDateTimeBehavior=convertToNull&characterEncoding=utf-8&allowMultiQueries=true
    username: developer
    password: developer
#日记输出到logstash的tcp地址
logstash:
  destination: 172.16.2.5:4567
logging:
  config: http://fsconfigserver:8888/fs-logback/default/master/logback-spring.xml