eureka:
  instance:
    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/plat_sys
    username: andy
    password: "{cipher}85b1e11113f493967e62ee6c3f7f8be0cb3fcf87e02333c4392d49accc5b9b69"
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: "{cipher}2df160dcfd591bcc30397e5884b385ce2da74e1247299bc69e99468d92b3eb23"
logging:
  config: http://127.0.0.1:8888/fs-logback/default/master/logback-spring.xml
logstash:
  destination: 127.0.0.1:4567