eureka:
  instance:
    prefer-ip-address: false
    hostname: fsfinance
  client:
    service-url:
      defaultZone: http://bseurekaserver:9761/eureka/,http://bseurekaserver2:9762/eureka/
spring:
  datasource:
    url: jdbc:mysql://172.16.2.3:3306/finance
    username: developer
    password: "{cipher}1ce9b466bb25531a0d4ed5cf5749d37428b854cadac09ec43d9499aa32dd5d09"
  redis:
    host: 172.16.2.6
    port: 6379
  rabbitmq:
    host: 192.168.63.195
    port: 5672
    username: guest
    password: "{cipher}eb95f8788faf8ede3c482a026f6f70b5d87c16a77665e8af0ba493e6cc19aed6"
  zipkin:
    base-url: http://bszipkinserver:9411
logging:
  config: http://bsconfigserver:9888/bs-logback/default/master/logback-spring.xml
logstash:
  destination: 172.16.2.5:4567
uca:
  fs-finance:
    hxb-pay-password: "{cipher}3b07d6d1ac32defad3b8adca32d3bbdae4ed75deda4897bb24f334c6eab3c049"
    hxb-pay-url: http://172.16.2.6:9070/ucacc-pay
    cgb-pay-url: http://172.16.2.6:9080/cgbpay/v1
    cgb-pay-name: ucacc_01
    cgb-pay-password: "{cipher}8432427924d7d11d6f7b7b6080530433682a49550f1c2e89c5fdf7cf9477b150"
    universal-security-code: "000000"
    temp-file-path: /opt/uca/file/temp
    temp-file-url: http://file.ucacc-dev.com/fs-plat-file/raw-material/temp
    eletronic-receipt-file-url: http://testfile.ucacc.com/bs-plat-file/raw-material/ElectronicReceipt/20000222
    bill:
      payment-credential-corporates:
        - e6b190a9ef2b471cae78890da2f67987
        - 807cbe43791f4ca8a59dd6a6d9afa5f8
        - d6ca9c6526df46c8be489dce6938a00e
    pay-apply:
      pay-code-prefix: -T1-