eureka:
  instance:
    prefer-ip-address: false
    hostname: tfinance
  client:
    service-url:
      defaultZone: http://bseurekaserver:9761/eureka/,http://bseurekaserver2:9762/eureka/
spring:
  datasource:
    url: jdbc:mysql://172.16.2.3:3306/finance
    username: developer
    password: "{cipher}1ce9b466bb25531a0d4ed5cf5749d37428b854cadac09ec43d9499aa32dd5d09"
  rabbitmq:
    host: 172.16.2.6
    port: 5672
    username: guest
    password: "{cipher}eb95f8788faf8ede3c482a026f6f70b5d87c16a77665e8af0ba493e6cc19aed6"
  redis:
    host: 172.16.2.6
    port: 6379
  zipkin:
    base-url: http://zipkinserver:9411
logging:
  config: http://bsconfigserver:9888/bs-logback/default/master/logback-spring.xml
logstash:
  destination: 172.16.2.5:4567
uca:
  t-finance:
    scheduler:
      offline-payapply-auto-confirm:
        cron: '23 0/10 * * * ?'
      third-party-payapply:
        cron: '13 0/10 * * * ?'
