eureka:
  instance:
    prefer-ip-address: false
    hostname: bsplatcode
  client:
    serviceUrl:
      defaultZone: http://bseurekaserver:9761/eureka/,http://bseurekaserver2:9762/eureka/
spring:
  redis:
    host: 172.16.2.6
    port: 6379
    database: 1
  zipkin:
    base-url: http://zipkinserver:9411
logging:
  config: http://bsconfigserver:9888/bs-logback/default/master/logback-spring.xml
logstash:
  destination: 172.16.2.5:4567