eureka:
  instance:
    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://127.0.0.1:9761/eureka/
spring:
  redis:
    host: 127.0.0.1
    port: 6379
logging:
  config: http://127.0.0.1:9888/bs-logback/default/master/logback-spring.xml
logstash:
  destination: 127.0.0.1:4567