eureka:
  instance:
    prefer-ip-address: false
    hostname: fsauthserver
  client:
    serviceUrl:
      defaultZone: http://fseurekaserver:8761/eureka/,http://fseurekaserver2:8762/eureka/
spring:
  datasource:
    url: jdbc:mysql://rm-wz9y4h9rwvs17i4cv.mysql.rds.aliyuncs.com:3306/fs_auth
    username: ucacc1018
    password: "{cipher}d3e57249863c5a031cb73e111c6eb5985d1ce868c799887bb86912ff1c16b584"
  rabbitmq:
    host: 172.16.2.6
    port: 5672
    username: guest
    password: "{cipher}eb95f8788faf8ede3c482a026f6f70b5d87c16a77665e8af0ba493e6cc19aed6"
  redis:
    host: 172.16.2.6
    port: 6379
  zipkin:
    base-url: http://fszipkinserver:8411
logging:
  config: http://fsconfigserver:8888/fs-logback/default/master/logback-spring.xml
logstash:
  destination: 172.16.2.5:4567
auth-server:
  universal-security-code: "000000"
  clients:
    fs-web:
      access-token-validity-seconds: 120 # 30 mins
      refresh-token-validity-seconds: 2592000 # 30 day
      client-secret: "{cipher}a077a21a66e4630028f92739cd81fe60a1a3e1cee07809859648f9fbc741870af4ffb80ef1bd5d91ccb095860add9816"
    fs-mobile:
      access-token-validity-seconds: 1800 # 30 mins
      refresh-token-validity-seconds: 7776000 #90 day
      client-secret: "{cipher}a077a21a66e4630028f92739cd81fe60a1a3e1cee07809859648f9fbc741870af4ffb80ef1bd5d91ccb095860add9816"
  wechat:
    mini-appid: wxb2fe5e5684caea22
    mini-secret: 104c7c5352fc81995fe8c0681c418b7e
seata:
  service:
    grouplist:
      fs_seata: fsseataserver:8091