eureka:
  instance:
    prefer-ip-address: false
    hostname: trawmaterial
  client:
    service-url:
      defaultZone: http://bseurekaserver:9761/eureka/
spring:
  zipkin:
    base-url: http://bszipkinserver:9411
  rabbitmq:
    host: 172.16.2.6
    port: 5672
    username: guest
    password: "{cipher}eb95f8788faf8ede3c482a026f6f70b5d87c16a77665e8af0ba493e6cc19aed6"
uca:
  back-staging-url: https://testadminhxxt.ucacc.com/
  global:
    mq:
      enable: false
    schedule:
      enable: true
  jdbc:
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 10
    maxIdle: 15
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    maxOpenPreparedStatements: 20
    removeAbandonedTimeout: 1800

    ## 测试环境
    url: jdbc:mysql://172.16.2.3:3306/masterdb3?zeroDateTimeBehavior=convertToNull&characterEncoding=utf-8&allowMultiQueries=true
    username: developer
    password: developer
  # nc定时任务(最大频次建议为每5分钟一次)
  scheduler:
    nc:
      # 应收单、应付单
      recPayBill:
        cron: '0 */10 * * * ?'
      # 收票登记
      regInvoice:
        cron: '10 */10 * * * ?'
      # 付款单
      rpaPayer:
        cron: '20 */10 * * * ?'
      # 收款单
      rpaPayee:
        cron: '30 */10 * * * ?'
      # 贴现单
      findiscount:
        cron: '50 */10 * * * ?'
#日记输出到logstash的tcp地址
logstash:
  destination: 172.16.2.5:4567
logging:
  config: http://bsconfigserver:9888/bs-logback/default/master/logback-spring.xml