eureka:
  instance:
    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/raw_material_sys
    username: andy
    password: "{cipher}b8f8a0ca8db128aabad7bd1ab0f33f1c78d5934e41e30a1b03c0737c1f0cd10f"
  redis:
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: "{cipher}2df160dcfd591bcc30397e5884b385ce2da74e1247299bc69e99468d92b3eb23"
logging:
  config: http://127.0.0.1:8888/fs-logback/default/master/logback-spring.xml
logstash:
  destination: 127.0.0.1:4567