eureka:
  instance:
    ip-address: 192.168.100.212
  client:
    service-url:
      defaultZone: http://192.168.63.195:8761/eureka/
spring:
  redis:
    host: 192.168.100.212
    port: 6379
  zipkin:
    base-url: http://192.168.63.195:8411
logging:
  config: http://192.168.63.195:8888/fs-logback/default/master/logback-spring.xml
logstash:
  destination: 192.168.63.195:4567