eureka:
  instance:
    prefer-ip-address: false
    hostname: bsecontract
  client:
    service-url:
      defaultZone: http://bseurekaserver:9761/eureka/,http://bseurekaserver2:9762/eureka/
spring:
  datasource:
    url: jdbc:mysql://172.16.2.3:3306/econtract
    username: developer
    password: "{cipher}1ce9b466bb25531a0d4ed5cf5749d37428b854cadac09ec43d9499aa32dd5d09"
  rabbitmq:
    host: 172.16.2.6
    port: 5672
    username: guest
    password: "{cipher}eb95f8788faf8ede3c482a026f6f70b5d87c16a77665e8af0ba493e6cc19aed6"
  redis:
    host: 172.16.2.6
    port: 6379
  zipkin:
    base-url: http://zipkinserver:9411
logging:
  config: http://bsconfigserver:9888/bs-logback/default/master/logback-spring.xml
logstash:
  destination: 172.16.2.5:4567
uca:
  econtract:
    developer-id: 2110673409741423137
    private-key: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBALUcbIUESOQPYJUNIB6FXR7TJziZrhNIxau5Br+ZsTFx6MNzQQnM4Ie5G5vNpABkFVsiaWfoQwIRI86zdtYszCqaMkmG5EicsSXHBfsPKUbnqtwjDsrCkax5DXFEAGh+8a/WOPlwpTCTBywNchwM3JOvhnhS78OMUeDsJ/zpuawRAgMBAAECgYAd+Fco592cB8NmxuZCxrTzLeP2pM++lzNGyHaKbEd7NCtddIwVsBaTvxkHfk8eVXGHRDmHHVNBW06+nMoUhRM/zjDToYeFyaMu92bpOemp158EMY7L7AcnX0TWKrD9/qBwuqIOVXtkur+sXm3QN1jnJjSf/Wg99oWoePzNCgy8QQJBAOEYpUpOFqEVS1+TVnwaDbEU+b8IBlu3kiAhoBcuqaBeopaQjAuZEwXfYE5zHYLxGIacZALuJQb29RrkqKnLbtkCQQDN+dlvSZCW3KK0i7h0TebG0Uee2efcc7eSlYd9hbJSBJXHv3F9RdlgM4xvIodZ/4iu4UsloRaVUkIUaexXrtP5AkEA0jXk7r58LZSoXipHgwAFt1ECZt9EqNSHN1CPo/ak3KpkJj35Oz+J31sbIkgo0Eb9g4B7ea0SkS2B+sp9pIviCQJBAJ7izoF0I97bz36qEN1WgmB3a2H0AVEiykZ+pgeDrGxsMQXmfar+yJHW8cuAvRwFa/BKxeb+/iatT1/j3XY93DECQFVcsDMpYPaS6JxcZ3o8OB9Zg7GxAJCpAlTsZJTNKxgqvIfpDpk78/DMjtIdyaOKthPU1j7t3XkENa3Gt4Hdj7k=
    sdk-client-host: https://ectest.ucacc.com/openapi/v2
    tmp-file-path: /opt/uca/file/raw-material/temp
    best-sign-contract-link-domain: https://t.bestsign.info/
    contract-link-msg-push-template: SMS_206551982
    contract-expired-seconds: 5184000 #6个月
    contract-link-expired-seconds: 604800 #7天
seata:
  service:
    grouplist:
      bs_seata: bsseataserver:9091