eureka:
  instance:
    prefer-ip-address: false
    hostname: bsopsmsgpush
  client:
    service-url:
      defaultZone: http://bseurekaserver:9761/eureka/,http://bseurekaserver2:9762/eureka/
spring:
  datasource:
    url: jdbc:mysql://120.77.46.84:3306/finance
    username: uca
    password: "{cipher}1ce9b466bb25531a0d4ed5cf5749d37428b854cadac09ec43d9499aa32dd5d09"
  rabbitmq:
    host: 172.16.2.6
    port: 5672
    username: guest
    password: "{cipher}eb95f8788faf8ede3c482a026f6f70b5d87c16a77665e8af0ba493e6cc19aed6"
  redis:
    host: 172.16.2.6
    port: 6379
  zipkin:
    base-url: http://bszipkinserver:9411
logging:
  config: http://bsconfigserver:9888/bs-logback/default/master/logback-spring.xml
logstash:
  destination: 172.16.2.5:4567
uca:
  bs-finance:
    hxb-pay-password: "{cipher}3b07d6d1ac32defad3b8adca32d3bbdae4ed75deda4897bb24f334c6eab3c049"
    hxb-pay-url: http://172.16.2.6\:9070/ucacc-pay
    cgb-pay-url: http://172.16.2.6\:9080/cgbpay/v1
    cgb-pay-name: ucacc_01
    cgb-pay-password: "{cipher}8432427924d7d11d6f7b7b6080530433682a49550f1c2e89c5fdf7cf9477b150"
    eletronic-receipt-file-url: http://testfile.ucacc.com/bs-plat-file/raw-material/ElectronicReceipt/20000222
    pay-apply:
      pay-code-prefix: -T1-