eureka:
  instance:
    prefer-ip-address: false
    hostname: fsspringbootadminserver
  client:
    service-url:
      defaultZone: http://fseurekaserver:8761/eureka/
logging:
  config: http://fsconfigserver:8888/fs-logback/default/master/logback-spring.xml
logstash:
  destination: 172.16.2.5:4567
spring:
  security:
    user:
      password: "{cipher}4b90b112ccdc872c8dbb3f6fd6e4eae0d6e7a9a95a5ab09835e8f7726b3740ba"