eureka:
  instance:
    ip-address: 192.168.63.195
  client:
    service-url:
      defaultZone: http://192.168.63.195:8761/eureka/
logging:
  config: http://192.168.63.195:8888/fs-logback/default/master/logback-spring.xml
logstash:
  destination: 192.168.63.195:4567
spring:
  security:
    user:
      password: "{cipher}4b90b112ccdc872c8dbb3f6fd6e4eae0d6e7a9a95a5ab09835e8f7726b3740ba"