eureka:
  instance:
    prefer-ip-address: false
    hostname: bsauthserver
  client:
    serviceUrl:
      defaultZone: http://bseurekaserver:9761/eureka/,http://bseurekaserver2:9762/eureka/
spring:
  datasource:
    url: jdbc:mysql://rm-wz9y4h9rwvs17i4cv.mysql.rds.aliyuncs.com:3306/bs_auth
    username: ucacc1018
    password: "{cipher}d3e57249863c5a031cb73e111c6eb5985d1ce868c799887bb86912ff1c16b584"
  rabbitmq:
    host: 172.16.2.6
    port: 5672
    username: guest
    password: "{cipher}eb95f8788faf8ede3c482a026f6f70b5d87c16a77665e8af0ba493e6cc19aed6"
  redis:
    host: 172.16.2.6
    port: 6379
  zipkin:
    base-url: http://bszipkinserver:9411
logging:
  config: http://bsconfigserver:9888/bs-logback/default/master/logback-spring.xml
logstash:
  destination: 172.16.2.5:4567
auth-server:
  universal-security-code: "000000"
  clients:
    bs-web:
      access-token-validity-seconds: 120 # 30 mins
      refresh-token-validity-seconds: 2592000 # 30 day
      client-secret: "{cipher}721a1464c48aab71370deab42cafb508cd4c08a4dc5c81af6a9aacfca376c1c5"
    bs-mobile:
      access-token-validity-seconds: 1800 # 30 mins
      refresh-token-validity-seconds: 7776000 #90 day
      client-secret: "{cipher}721a1464c48aab71370deab42cafb508cd4c08a4dc5c81af6a9aacfca376c1c5"
seata:
  service:
    grouplist:
      bs_seata: bsseataserver:9091