eureka:
  instance:
    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://127.0.0.1:9761/eureka/
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/plat_msgpush
    username: andy
    password: "{cipher}ba650aff4c287756d58513e7ad127edfc125d6307ce0c1757120f85eadb165ea"
logging:
  config: http://127.0.0.1:9888/bs-logback/default/master/logback-spring.xml
logstash:
  destination: 127.0.0.1:4567
uca:
  plat:
    msg-push:
      bs:
        sms-msg-push:
          password: "{cipher}d83c03af3c18c1eaa93591065a5977b72dbc68b24c5ee8aa1e0298ab3786015d"