eureka:
  instance:
    ip-address: 192.168.100.212
  client:
    service-url:
      defaultZone: http://192.168.63.195:9761/eureka/
spring:
  redis:
    host: 192.168.63.195
    port: 6379
  zipkin:
    base-url: http://192.168.63.195:9411
logging:
  config: http://192.168.63.195:9888/bs-logback/default/master/logback-spring.xml
uca:
  oauth2:
    auth-server:
      universal-security-code: "000000"
      web:
        timeout: 86400 # 1 day
        secret: "{cipher}721a1464c48aab71370deab42cafb508cd4c08a4dc5c81af6a9aacfca376c1c5"
      mobile:
        timeout: 86400 # 1 day
        secret: "{cipher}721a1464c48aab71370deab42cafb508cd4c08a4dc5c81af6a9aacfca376c1c5"
logstash:
  destination: 192.168.63.195:4567