eureka:
  instance:
    ip-address: 192.168.100.212
  client:
    service-url:
      defaultZone: http://192.168.63.195:9761/eureka/
spring:
  datasource:
    url: jdbc:mysql://192.168.63.195:3306/bs_plat_corporate_ops_sys
    username: uca
    password: "{cipher}698554aab5fb42360efdd645be1dcfc47d2200496fd6a9329898dcf7fbaa7748"
  zipkin:
    base-url: http://192.168.63.195:9411
logging:
  config: http://192.168.63.195:9888/bs-logback/default/master/logback-spring.xml
logstash:
  destination: 192.168.63.195:4567