eureka:
  instance:
    ip-address: 192.168.100.207
  client:
    service-url:
      defaultZone: http://192.168.63.195:9761/eureka/
spring:
  zipkin:
    base-url: http://192.168.63.195:9411
  rabbitmq:
    host: 192.168.63.195
    port: 5672
    username: guest
    password: "{cipher}2df160dcfd591bcc30397e5884b385ce2da74e1247299bc69e99468d92b3eb23"
uca:
  jdbc:
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 10
    maxIdle: 15
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    maxOpenPreparedStatements: 20
    removeAbandonedTimeout: 1800
    # 开发环境
    url: jdbc:mysql://192.168.63.195:3306/raw_material?zeroDateTimeBehavior=convertToNull&characterEncoding=utf-8&allowMultiQueries=true
    username: uca
    password: "{cipher}40963fb09c296aa686132840b06a234ae70e9bbdaf22e53c602f17841c939c9c"
    ## 测试环境
    #url: jdbc:mysql://120.77.46.84:3307/masterdb_docker?zeroDateTimeBehavior=convertToNull&characterEncoding=utf-8&allowMultiQueries=true
    #username: developer
    #password: developer
#日记输出到logstash的tcp地址
logstash:
  destination: 192.168.63.195:4567
logging:
  config: http://192.168.63.195:9888/bs-logback/default/master/logback-spring.xml