eureka:
  instance:
    prefer-ip-address: false
    hostname: fsrawmaterialopssys
  client:
    serviceUrl:
      defaultZone: http://fseurekaserver:8761/eureka/,http://fseurekaserver2:8762/eureka/
spring:
  datasource:
    url: jdbc:mysql://rm-wz9y4h9rwvs17i4cv.mysql.rds.aliyuncs.com:3306/bs_raw_material_ops_sys
    username: ucacc1018
    password: "{cipher}bce2707ccb18fd06160cb677511d9c4164c20c069a39bf1e6706a7c663b2c519"
  zipkin:
    base-url: http://fszipkinserver:8411
logging:
  config: http://fsconfigserver:8888/fs-logback/default/master/logback-spring.xml
logstash:
  destination: 172.16.2.5:4567