eureka:
  instance:
    prefer-ip-address: false
    hostname: fsplatcorporate
  client:
    serviceUrl:
      defaultZone: http://fseurekaserver:8761/eureka/,http://fseurekaserver2:8762/eureka/
spring:
  datasource:
    url: jdbc:mysql://rm-wz9y4h9rwvs17i4cv.mysql.rds.aliyuncs.com:3306/plat_corporate
    username: ucacc1018
    password: "{cipher}d3e57249863c5a031cb73e111c6eb5985d1ce868c799887bb86912ff1c16b584"
  redis:
    host: 172.16.2.6
    port: 6379
  rabbitmq:
    host: 172.16.2.6
    port: 5672
    username: guest
    password: "{cipher}eb95f8788faf8ede3c482a026f6f70b5d87c16a77665e8af0ba493e6cc19aed6"
  zipkin:
    base-url: http://fszipkinserver:8411
logging:
  config: http://fsconfigserver:8888/fs-logback/default/master/logback-spring.xml
logstash:
  destination: 172.16.2.5:4567
seata:
  service:
    grouplist:
      fs_seata: fsseataserver:8091
uca:
  plat:
    corporate:
      fs:
        universal-security-code: "000000"
        temp-file-path: /opt/uca/file/raw-material/temp
        temp-file-url: https://testfile.ucacc.com/fs-plat-file/raw-material/temp
        qcc:
          url: http://api.qichacha.com/ECIV4/Search
          appkey: e5e7ac93ccf240a5991e058c19dcf267
          seckey: E5CD8323D645CEECBBB7E5EC4B75CFF6