eureka:
  instance:
    prefer-ip-address: false
    hostname: fsecontract
  client:
    service-url:
      defaultZone: http://fseurekaserver:8761/eureka/,http://fseurekaserver2:8762/eureka/
spring:
  datasource:
    url: jdbc:mysql://172.16.2.3:3306/econtract
    username: developer
    password: "{cipher}1ce9b466bb25531a0d4ed5cf5749d37428b854cadac09ec43d9499aa32dd5d09"
  rabbitmq:
    host: 172.16.2.6
    port: 5672
    username: guest
    password: "{cipher}eb95f8788faf8ede3c482a026f6f70b5d87c16a77665e8af0ba493e6cc19aed6"
  redis:
    host: 172.16.2.6
    port: 6379
  zipkin:
    base-url: http://zipkinserver:9411
logging:
  config: http://fsconfigserver:8888/fs-logback/default/master/logback-spring.xml
logstash:
  destination: 172.16.2.5:4567
uca:
  econtract:
    tmp-file-path: /opt/uca/file/raw-material/temp
    universal-security-code: "000000"
    best-sign-contract-link-domain: https://t.bestsign.info/
    contract-link-msg-push-template: SMS_206551982
seata:
  service:
    grouplist:
      fs_seata: fsseataserver:8091