eureka:
  instance:
    prefer-ip-address: false
    hostname: bsopssys
  client:
    serviceUrl:
      defaultZone: http://bseurekaserver:9761/eureka/,http://bseurekaserver2:9762/eureka/
spring:
  datasource:
    url: jdbc:mysql://rm-wz9y4h9rwvs17i4cv.mysql.rds.aliyuncs.com:3306/ops_sys
    username: ucacc1018
    password: "{cipher}bce2707ccb18fd06160cb677511d9c4164c20c069a39bf1e6706a7c663b2c519"
  rabbitmq:
    host: 172.16.2.6
    port: 5672
    username: guest
    password: "{cipher}eb95f8788faf8ede3c482a026f6f70b5d87c16a77665e8af0ba493e6cc19aed6"
  zipkin:
    base-url: http://bszipkinserver:9411
logging:
  config: http://bsconfigserver:9888/bs-logback/default/master/logback-spring.xml
logstash:
  destination: 172.16.2.5:4567
seata:
  service:
    grouplist:
      bs_seata: bsseataserver:9091