eureka:
  instance:
    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://127.0.0.1:9761/eureka/
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ops_sys
    username: andy
    password: "{cipher}ba650aff4c287756d58513e7ad127edfc125d6307ce0c1757120f85eadb165ea"
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: "{cipher}257b9b2287a88191dd6e43979c7ef67d87c82b15d60da332c8ca4b22285fc03e"
logging:
  config: http://127.0.0.1:9888/bs-logback/default/master/logback-spring.xml
logstash:
  destination: 127.0.0.1:4567